---
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - python_requirement

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common

- hosts: jenkins_master
  become: yes
  gather_facts: yes
  roles:
    - jenkins

- hosts: jenkins_build
  become: yes
  gather_facts: yes
  vars:
    - install_f5fpc: true
  roles:
    - jenkins_build_node
