---
- name: Wait for machine to come back
  local_action: wait_for host="{{ ansible_ssh_host | default(inventory_hostname) }}" state=started port=22 search_regex=OpenSSH delay=30 timeout=600
  become: no
