---
- name: Add Java PPA for Ubuntu 14.04
  apt_repository:
    repo: 'ppa:webupd8team/java'
  when:
    - ansible_distribution_release == 'trusty'

- name: Install Java from PPA Auto-Accept for Ubuntu 14.04
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  when:
    - ansible_distribution_release == 'trusty'

- name: Install Java from PPA for Ubuntu 14.04
  apt:
    name: oracle-java8-set-default
    update_cache: yes
    state: latest
  when:
    - ansible_distribution_release == 'trusty'

- name: Install Java 8 on Ubuntu 16.04
  apt:
    name: openjdk-8-jre-headless
    update_cache: yes
    state: latest
  when:
    - ansible_distribution_release == 'xenial'

- name: Install Elasticsearch repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elasticsearch
  apt:
    deb: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.4/elasticsearch-2.3.4.deb
    state: present

- name: Pause before Elasticsearch Restart
  pause: seconds=10
  notify:
    - Restart Elasticsearch

- name: Ensure elasticsearch running
  service:
    name: elasticsearch
    state: running

- name: Install Kibana
  apt:
    deb: https://download.elastic.co/kibana/kibana/kibana_4.5.3_amd64.deb
    state: present

- name: Update Kibana configuration
  copy:
    src: kibana.yml
    dest: /opt/kibana/config/kibana.yml
    force: yes
  notify:
    - Restart Kibana

- name: Get Kibana Dashboards
  git:
    repo: https://github.com/lamarwhitej/kibana_import_objects.git
    dest: /root/kibana_import_objects

- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
    state: latest
  when:
    - ansible_distribution | lower == 'ubuntu'

- name: install plugins
  command: bin/kibana plugin -i {{ item.name }} -u {{ item.url}}
  args:
    chdir: /opt/kibana
  with_items:
    - { name: 'kibana-time-plugin', url: 'https://github.com/nreese/kibana-time-plugin/archive/4.x.zip' }
    - { name: 'heatmap', url: 'https://github.com/stormpython/heatmap/archive/1.0.0.zip' }
    - { name: 'kibana-html-plugin', url: 'https://github.com/raystorm-place/kibana-html-plugin/releases/download/v0.0.3/kibana-html-plugin-v0.0.3.tar.gz' }

- name: Install Dashboards Requirements
  pip:
    requirements: requirements.txt
    chdir: /root/kibana_import_objects

- name: Upload Dashboards
  shell: |
    cd /root/kibana_import_objects
    python import_objects.py -s json/search.json -v json/visual.json -d json/dashboard.json
    python import_objects.py -i osa_onmetal_upgrade_tests -m json/index_osa_mapping.json -p json/index_osa_pattern.json
    python import_objects.py -i osa_onmetal_upgrade_status_log -m json/index_status_mapping.json -p json/index_status_pattern.json
  notify:
    - Restart Kibana

- name: Ensure kibana running
  service:
    name: kibana
    state: running
